run:
  timeout: 1m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - asciicheck
    - errorlint
    - depguard
    - goconst
    - makezero
    - nonamedreturns
    - predeclared
    - gocritic
    - importas

issues:
  # Do not limit the number of issues per linter.
  max-issues-per-linter: 0

  # Do not limit the number of times a same issue is reported.
  max-same-issues: 0

  exclude-rules:
    - linters:
        - govet
      text: 'declaration of "err"'
    - path: _test\.go
      linters:
        - errcheck
        - gosec


# output configuration options
output:
  formats:
    - format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

linters-settings:

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/aws/aws-sdk-go/aws"
            desc: "dont use"

  gocritic:
    disabled-checks:
      - newDeref # it's wrong on generics
      - singleCaseSwitch # sometimes i like them, leave me be
      - ifElseChain # sometimes, i just want to.

  # govet:
  #   check-shadowing: true
    # enable-all: true

  importas:
    no-unaliased: true
    # no-extra-aliases: true
    alias:
        # AWS Resource Types
      - pkg: github.com/aws/aws-sdk-go-v2/service/kms/types
        alias: kmsTypes
