name: golangci-lint Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --config .golangci.yml --timeout 5m --verbose
      
  